language: objective-c
osx_image: xcode10
rvm:
  - 2.4.1
cache:
  - bundler
  - cocoapods
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec fastlane setup
script:
  - bundle exec fastlane codeclimate_before_build
  - bundle exec fastlane test
  - bundle exec fastlane coverage_xml
  - bundle exec fastlane codeclimate_after_build
  - bundle exec fastlane pod_lint
